export const ADD_SCHOLARSHIP = "ADD_SCHOLARSHIP";
export const REMOVE_SCHOLARSHIP = "REMOVE_SCHOLARSHIP";
export const CHANGE_STATUS_ACTIVE = "CHANGE_STATUS_ACTIVE";
export const CHANGE_STATUS_INACTIVE = "CHANGE_STATUS_INACTIVE";
export const APPROVE_SCHOLARSHIP = "APPROVE_SCHOLARSHIP";
