export const data = [
  {
    sch_id: 1,
    sch_name: "national scholarship1",
    gov_or_private: "government",
    nat_or_reg: "national",
    eligiblity: "this all is criteria",
    income_limit: "120000",
    deadline: "12th oct",
    link_to_apply: "http://schadd.com",
    active_inactive: "yes",
    procedure: "this is procedure",
  },
  {
    sch_id: 2,
    sch_name: "national scholarship2",
    gov_or_private: "government",
    nat_or_reg: "national",
    eligiblity: "this all is criteria",
    income_limit: "120000",
    deadline: "12th oct",
    link_to_apply: "http://schadd.com",
    active_inactive: "yes",
    procedure: "this is procedure",
  },
  {
    sch_id: 3,
    sch_name: "national scholarship3",
    gov_or_private: "government",
    nat_or_reg: "national",
    eligiblity: "this all is criteria",
    income_limit: "120000",
    deadline: "12th oct",
    link_to_apply: "http://schadd.com",
    active_inactive: "yes",
    procedure: "this is procedure",
  },
  {
    sch_id: 4,
    sch_name: "national scholarship4",
    gov_or_private: "government",
    nat_or_reg: "national",
    eligiblity: "this all is criteria",
    income_limit: "120000",
    deadline: "12th oct",
    link_to_apply: "http://schadd.com",
    active_inactive: "yes",
    procedure: "this is procedure",
  },
  {
    sch_id: 5,
    sch_name: "national scholarship5",
    gov_or_private: "government",
    nat_or_reg: "national",
    eligiblity: "this all is criteria",
    income_limit: "120000",
    deadline: "12th oct",
    link_to_apply: "http://schadd.com",
    active_inactive: "yes",
    procedure: "this is procedure",
  },
  {
    sch_id: 6,
    sch_name: "national scholarship6",
    gov_or_private: "government",
    nat_or_reg: "national",
    eligiblity: "this all is criteria",
    income_limit: "120000",
    deadline: "12th oct",
    link_to_apply: "http://schadd.com",
    active_inactive: "yes",
    procedure: "this is procedure",
  },
  {
    sch_id: 7,
    sch_name: "national scholarship7",
    gov_or_private: "government",
    nat_or_reg: "national",
    eligiblity: "this all is criteria",
    income_limit: "120000",
    deadline: "12th oct",
    link_to_apply: "http://schadd.com",
    active_inactive: "yes",
    procedure: "this is procedure",
  },
  {
    sch_id: 8,
    sch_name: "national scholarship8",
    gov_or_private: "government",
    nat_or_reg: "national",
    eligiblity: "this all is criteria",
    income_limit: "120000",
    deadline: "12th oct",
    link_to_apply: "http://schadd.com",
    active_inactive: "yes",
    procedure: "this is procedure",
  },
  {
    sch_id: 9,
    sch_name: "national scholarship9",
    gov_or_private: "government",
    nat_or_reg: "national",
    eligiblity: "this all is criteria",
    income_limit: "120000",
    deadline: "12th oct",
    link_to_apply: "http://schadd.com",
    active_inactive: "yes",
    procedure: "this is procedure",
  },
  {
    sch_id: 10,
    sch_name: "national scholarship10",
    gov_or_private: "government",
    nat_or_reg: "national",
    eligiblity: "this all is criteria",
    income_limit: "120000",
    deadline: "12th oct",
    link_to_apply: "http://schadd.com",
    active_inactive: "yes",
    procedure: "this is procedure",
  },
  {
    sch_id: 11,
    sch_name: "national scholarship11",
    gov_or_private: "government",
    nat_or_reg: "national",
    eligiblity: "this all is criteria",
    income_limit: "120000",
    deadline: "12th oct",
    link_to_apply: "http://schadd.com",
    active_inactive: "yes",
    procedure: "this is procedure",
  },
  {
    sch_id: 12,
    sch_name: "national scholarship12",
    gov_or_private: "government",
    nat_or_reg: "national",
    eligiblity: "this all is criteria",
    income_limit: "120000",
    deadline: "12th oct",
    link_to_apply: "http://schadd.com",
    active_inactive: "yes",
    procedure: "this is procedure",
  },
];
